# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-12-20 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBackDatamodels',
            new_name='FeedbackData',
        ),
    ]
